export const URL_IMG_PROJECT = '/assets/sites/{}.jpg'
export const URL_IMG_CMS = '/assets/icons/{}.svg'
export const URL_ALL_PROJECTS = 'https://script.google.com/macros/s/AKfycbxmXBEcD3U0-e9nTwJ02EkAKXLsxTYkkYt6t9Wni6m_Fgr7OaWnTc_WEPLu2Up1M8w/exec'
export const GET_PARM_GET_SERVICES = '?get=services'
export const GET_PARAM_GET_FTP = '?get=ftp'